#!/bin/bash

## Configures database into container
##
## Usage: fin db-configure [optional params]


#--------------------- DB Config -----------------------------

cd $PROJECT_ROOT/$DOCROOT &&
     fin drush updb $1

#--------------------- END: DB Config ------------------------