#!/bin/bash

## Initializes the site
##
## Usage: fin init


#-------------------- Paths -----------------------------------

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
PARENT_PATH="$(dirname "$DOCROOT_PATH")"

#-------------------- END: Paths ------------------------------


#-------------------- Docker Check ----------------------------

if [ "$DOCKER_RUNNING" == true ]; then
        echo "Docker is running.  Resetting services."
        fin reset -f
else
        echo "Docker is not running. Starting containers."
        fin up
fi

#--------------------- END: Docker Check -----------------------


#--------------------- Composer Install ------------------------

if [ 'which composer' ]; then
        cd ${PARENT_PATH}
        echo "Installing all libraries and dependencies."
        composer install
else
        echo "Unable to determine if composer is installed. Aborting install."
        exit 1
fi

#--------------------- END: Composer Install --------------------


#--------------------- Site Install -----------------------------

cd ${DOCROOT_PATH} &&
     IP=$(fin vm ip) &&
     fin drush site-install --db-url=mysql://user:user@$IP:33061/default &&
     fin drush uli

#--------------------- END: Site Install ------------------------