#!/bin/bash

## Initializes the site
##
## Usage: fin init

# Check for running containers
if [ "$DOCKER_RUNNING" == true ]; then
        echo "Docker is running.  Resetting services."
        fin reset -f
else
        echo "Docker is not running. Starting containers."
        fin up
fi

# Check for composer
if [ 'which composer' ]; then
        echo "Installing all libraries and dependencies."
        composer install
else
        echo "Unable to determine if composer is installed. Aborting install."
        exit 1
fi

# Install the site via drush
cd $PROJECT_ROOT/$DOCROOT &&
     IP=$(fin vm ip) &&
     fin drush site-install --db-url=mysql://user:user@$IP:33061/default &&
     fin drush uli