# Custom Stack for D8

version: "2.1"

services:
  # Web
  web:
    hostname: web
    image: docksal/web:2.1-apache2.4
    volumes:
      - project_root:/var/www:ro,nocopy
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
      - APACHE_BASIC_AUTH_USER
      - APACHE_BASIC_AUTH_PASS
    depends_on:
      - cli
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # DB
  db:
    hostname: db
    image: mariadb
    command: mysqld --max-allowed-packet=1G
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
      - project_root:/var/www:ro,nocopy
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # CLI
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: docksal/cli:2.0-php7.2
    volumes:
      - project_root:/var/www:rw,nocopy
      - docksal_ssh_agent:/.ssh-agent:ro
      - /home/docker
    environment:
      - HOST_UID
      - HOST_GID
      - DOCROOT
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
      - XDEBUG_CONFIG=remote_connect_back=0 remote_host=${DOCKSAL_HOST_IP}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Solr
  solr:
    hostname: solr
    image: docksal/solr:1.0-solr4
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Redis
  redis:
    hostname: redis
    image: redis:alpine
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Selenium
  browser:
    hostname: browser
    image: selenium/standalone-firefox
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}