# Custom Stack for D8

version: "2.1"

services:
  # Web
  web:
    hostname: web
    image: ${WEB_IMAGE:-docksal/nginx:1.15-1.0}
    volumes:
      - project_root:/var/www:ro,nocopy
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST},${VIRTUAL_HOST}.*
      - io.docksal.cert-name=${VIRTUAL_HOST_CERT_NAME:-none}
      - io.docksal.project-root=${PROJECT_ROOT}
      - io.docksal.permanent=${SANDBOX_PERMANENT:-false}
    environment:
      - NGINX_VHOST_PRESET=drupal
      - NGINX_FCGI_HOST_PORT=cli:9000
      - NGINX_SERVER_ROOT=/var/www/${DOCROOT}
      - NGINX_BASIC_AUTH_USER
      - NGINX_BASIC_AUTH_PASS
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # DB
  db:
    hostname: db
    image: mariadb
    command: mysqld --max-allowed-packet=1G
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
      - project_root:/var/www:ro,nocopy
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # CLI
  cli:
    hostname: cli
    image: ${CLI_IMAGE:-docksal/cli:2-php7.3}
    volumes:
      - project_root:/var/www:rw,nocopy
      - ${SSH_AUTH_SOCK:-docksal_ssh_agent}:${SSH_AUTH_SOCK:-/.ssh-agent}:ro
      - cli_home:/home/docker
    ports:
      - "2223:22"
    environment:
      - HOST_UID
      - HOST_GID
      - DOCROOT
      - VIRTUAL_HOST
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
      - XDEBUG_CONFIG=remote_connect_back=0 remote_host=${DOCKSAL_HOST_IP}
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
      - DRUSH_ALLOW_XDEBUG=${XDEBUG_ENABLED:-0}
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK:-/.ssh-agent/proxy-socket}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Solr
  solr:
    hostname: solr
    image: ${SOLR_IMAGE:-docksal/solr:1.0-solr4}
    volumes:
      - project_root:/var/www:ro,nocopy
    labels:
      - io.docksal.virtual-host=solr.${VIRTUAL_HOST},solr.${VIRTUAL_HOST}.*
      - io.docksal.virtual-port=8983
      - io.docksal.cert-name=${VIRTUAL_HOST_CERT_NAME:-none}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Redis
  redis:
    hostname: redis
    image: redis:alpine
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Selenium
  browser:
    hostname: browser
    image: selenium/standalone-firefox
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
