#!/bin/bash

## Runs Behat tests.
##
## Usage: fin behat

#-------------------- Paths -----------------------------------

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
PARENT_PATH="$(dirname "$DOCROOT_PATH")"

#-------------------- END: Paths ------------------------------


#-------------------- Helpers ---------------------------------

check_behat_install ()
{

  if [ ! -f "vendor/bin/behat" ]; then
    echo "Behat is not installed as a composer dependency."
    exit 1
  fi

}

check_behat_config ()
{

  if [ ! -f "behat.yml" ]; then
    echo "A behat.yml configuration file could not be found."
    exit 1
  fi

}

#-------------------- END: Helpers -----------------------------

#-------------------- Run Behat --------------------------------

cd ${PARENT_PATH}
check_behat_install
check_behat_config
fin exec "vendor/bin/behat -c behat.yml"

#-------------------- END: Run Behat ---------------------------